### ISSUE TITLE
[P0] wasm32 target fails to compile: architecture_config_from_qwen_config called from ungated code

### ISSUE THREAD

**Issue by astorise** [astorise/Magnetar#78]
## Summary

`cargo check --locked -p magnetar-runtime --target wasm32-unknown-unknown --all-features` fails:

```
error[E0425]: cannot find function `architecture_config_from_qwen_config` in this scope
   --> magnetar-runtime/src/first_native_runtime.rs:4223:22
```

`architecture_config_from_qwen_config` was gated `#[cfg(all(not(target_arch = "wasm32"), feature = "wasmtime-component-engine"))]`, but `E2eRuntimeModelExecutionEngine::execute_generation_step` (which calls it, added as part of #73's fix) is itself never `cfg`-gated — it must build for every target/feature combination this crate supports, wasm32 included.

Verified locally: this is a genuine regression, introduced by #73 (confirmed by reverting the change and reproducing the exact same error).

## Why it matters

This breaks the `quality / wasm32 component engine` CI job, which is part of the Quality CI Tachyon's vendored SHA is expected to be green on.

## Fix

`architecture_config_from_qwen_config` is a plain, portable struct-mapping function (`QwenConfig`/`ModelArchitectureConfig` are both always-available types, no Wasmtime dependency) — removing its `cfg` gate is sufficient and correct; it was only ever gated because, before #73, its only callers happened to live inside already-gated code.

Verified against `main` @ `1bb46a79a408f73b84b4c7963384a53d816ce3ab` (Tachyon integration audit, 18 septembre 2026, second round).

**Comment by astorise** [comment]
Fixed on `claude/gracious-gauss-6ojp6z` (commit `cce923b`, rebased onto latest `main` after PR #76 merged and picked up dependency updates).

Removed the `#[cfg(all(not(target_arch = "wasm32"), feature = "wasmtime-component-engine"))]` gate from `architecture_config_from_qwen_config` — it's a plain struct-mapping function with no Wasmtime dependency, and `E2eRuntimeModelExecutionEngine::execute_generation_step` (its calling site, itself never `cfg`-gated) needs it to compile unconditionally.

Verified: `cargo check --locked -p magnetar-runtime --target wasm32-unknown-unknown --all-features` now passes clean (previously reproduced the exact `E0425` error by reverting the fix locally, confirming this is the real cause).


---
_Generated by [Claude Code](https://claude.ai/code)_
